version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  ngrok:
    image: wernight/ngrok:latest
    container_name: ngrok
    environment:
      NGROK_AUTHTOKEN: 2qPjLMPo7bz2cydBfbz3m_7pzkGZyB2hMVdgkW7jaiz
      NGROK_PORT: http://wordpress:80
    volumes:
      - ngrok_logs:/home/ngrok/
    depends_on:
      - wordpress


volumes:
  wordpress_data:
  db_data:
  ngrok_logs:
