version: '3.8'


services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"  # SSL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
  ngrok:
    image: wernight/ngrok:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    environment:
      NGROK_AUTHTOKEN: xxxx
      NGROK_PORT: 80
    ports:
      - "4040:4040"  # Ngrok web interface
    command: 
      - bash -c 'ngrok http 80 > /ngrok_logs/ngrok_output.txt 2>&1'
    volumes:
      - ./ngrok.conf:/ngrok_logs/ngrok_output.txt
    
    


volumes:
  wordpress_data:
  db_data:

